### PR TITLE
Mauriziosacca patch 1

### PR DESCRIPTION
**Pull request by mauriziosacca**
Fix wrong constant import. Should solve Issue https://github.com/atxbyea/samsungrac/issues/87

### CODE REVIEW

**Comment by 5a2v0** [comment]
I can confirm that this PR is valid. After the update i get errors in my HA and CLIMATE IP can't start. I tried this and it works.

**In the climate.py file, row n. 317 there is a** 
`HVAC_MODE_OFF` 
that i think it must be changed in:
`HVACMode.OFF`

Is it correct?

**Review by 5a2v0 — APPROVED** [review]
I can confirm that this PR is valid. After the update i get errors in my HA and CLIMATE IP can't start. I tried this and it works.

**Review by 5a2v0 — CHANGES_REQUESTED** [review]
**In the climate.py file, row n. 317 there is:** 
`HVAC_MODE_OFF` 
that i think it must be changed in:
`HVACMode.OFF`

Is it correct?

**Comment by mauriziosacca** [comment]
Are you sure? I just checked, look at the screenshot

immagine

**Comment by 5a2v0** [comment]
> Maybe you mean in your repository, in my fork it is correct. I just checked, look at the screenshot
> 
> immagine

Ok sorry, maybe i see It on older climate.py files (previously the update!)

**Comment by atxbyea** [comment]
Thanks guys, my still limited knowledge of Python comes to show ;-) give me 80 more days!

**Pull request merged**
