### PR TITLE
Avoid blocking I/O in event loop on updates

### LINKED ISSUE #5: Performance - it brings down HA
Dear,

After testing Sebu's custom component and seeing HA performance issues. I was looking at the MQTT built from Sasha (https://github.com/gsasha/hvac_ip_mqtt_bridge) but there were bugs in the code.
Today I looked at your fork but still it seems not to be scalable enough for 6 A/Cs and more. Some of my components just don't work anymore. Also if I look my HDD moves to 90% utilisation. Anything you can do about it ?

I get the following error logs:

'Logger: custom_components.climate_ip.climate
Source: custom_components/climate_ip/samsung_2878.py:236
Integration: climate_ip (documentation, issues)
First occurred: 10:02:22 (224 occurrences)
Last logged: 10:29:58

Traceback (most recent call last): File "/config/custom_components/climate_ip/samsung_2878.py", line 219, in send_socket_command sslSocket = self.socket File "/config/custom_components/climate_ip/samsung_2878.py", line 281, in socket self.create_connection() File "/config/custom_components/climate_ip/samsung_2878.py", line 270, in create_connection sslSocket.connect((cfg.host, cfg.port)) File "/usr/local/lib/python3.8/ssl.py", line 1342, in connect self._real_connect(addr, False) File "/usr/local/lib/python3.8/ssl.py", line 1329, in _real_connect super().connect(addr) ConnectionRefusedError: [Errno 111] Connection refused

Logger: homeassistant.components.climate
Source: /usr/local/lib/python3.8/asyncio/events.py:81
Integration: Klimaat (documentation, issues)
First occurred: 10:02:34 (6 occurrences)
Last logged: 10:02:34

Setup of climate platform climate_ip is taking over 10 seconds.`

regards,
Jens

### PR DESCRIPTION
**Pull request by postlund**
Fixes #5.

### CODE REVIEW

**Comment by ishioni** [comment]
Are you sure? You're reverting my change from a while ago, which fixed HA complaining doing sync in an async context

**Comment by postlund** [comment]
Yeah, either the whole function is sync and do sync calls or it's entirely async and only do async calls. Using `asyncio.sleep` would work too, but since the library used to communicate with the devices is synchronous it's just easier to stick to the sync versions of all methods.

**Comment by atxbyea** [comment]
@postlund this PR  broke something it seems, my entity was not available anymore, expected subroutine got none, had to revert to 3.4 and so did another user

**Comment by postlund** [comment]
@atxbyea Can you provide a more extended error message?

**Comment by postlund** [comment]
@atxbyea I had to take a look at the change again and it was one of those WTH-have-I-done-kind-of moment. Hopefully #23 should solve the issues you are seeing.

**Pull request merged**
